import { getInput } from "@actions/core"
import { createPullRequest, getAllOpenPullRequests, setLabels, updateCommitStatusError, validateCommitMessages, writeCommentToPr } from "./JSLGhe"

const inputName: string = getInput("name")
const ghToken: string = getInput("ghToken")

greet(inputName)

//
function greet(name: string) {
    console.log(`'Hello ${name}!'`)
    // diff
    getAllOpenPullRequests(ghToken)

    writeCommentToPr(ghToken, 1, "test message from octokit")

    setLabels(ghToken, 1, ["test", "octokit", "actions"])

    validateCommitMessages(ghToken, "asd", 1)
    // workds
    // createPullRequest(ghToken, "generated by action", "feature/test", "master", "body test")

    //d93a68fb112e1eeb193aa5be4c81c754b39b6e36
    updateCommitStatusError(ghToken, "d93a68fb112e1eeb193aa5be4c81c754b39b6e36", "test-errors")
}


